{{- if .Values.kubescape.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.kubescape.name }}
spec:
  type: {{ .Values.kubescape.service.type }}
  ports:
    - name: http
      port: {{ .Values.kubescape.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.kubescape.name }}
{{ end }}