{{- if and .Values.global.networkPolicy.enabled .Values.gateway.enabled .Values.kubescape.submit }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.gateway.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.gateway.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  {{- if .Values.global.networkPolicy.createEgressRules }}
    - Egress
  egress:
      # gatewayUrl (wss://{{ .Values.gatewayUrl }}/v1)
    - ports:
      - port: 443
        protocol: TCP
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kubescape
              app.kubernetes.io/name: operator
              tier: ks-control-plane
      ports:
        - port: websocket
          protocol: TCP
{{- end }}
