apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: osreleasefiles.hostdata.kubescape.cloud
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
spec:
  group: hostdata.kubescape.cloud
  names:
    kind: OsReleaseFile
    listKind: OsReleaseFileList
    plural: osreleasefiles
    singular: osreleasefile
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: OsReleaseFile contains the OS release information from a node
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: OsReleaseFileSpec contains the actual OS release file content
            type: object
            properties:
              content:
                description: Content is the raw content of the OS release file
                type: string
              nodeName:
                description: NodeName is the name of the node this data came from
                type: string
          status:
            description: OsReleaseFileStatus contains status information about the sensing
            type: object
            properties:
              lastSensed:
                description: LastSensed is the timestamp when this data was last collected
                type: string
                format: date-time
              error:
                description: Error contains any error message from the last sensing attempt
                type: string
    additionalPrinterColumns:
    - name: Node
      type: string
      jsonPath: .spec.nodeName
    - name: Last Sensed
      type: string
      jsonPath: .status.lastSensed
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
