{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheusExporter.name }}
  labels:
    kubescape.io/ignore: "true"
subjects:
- kind: ServiceAccount
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheusExporter.name }}
{{- end }}
