{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.prometheusExporter.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  type: {{ .Values.prometheusExporter.service.type }}
  ports:
    - port: {{ .Values.prometheusExporter.service.port }}
      targetPort: {{ .Values.prometheusExporter.service.targetPort }}
      protocol: {{ .Values.prometheusExporter.service.protocol }}
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.prometheusExporter.name) | nindent 4 }}
{{- end }}
