{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
{{- if .Values.nodeAgent.config.hostSensor.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controlplaneinfos.hostdata.kubescape.cloud
spec:
  group: hostdata.kubescape.cloud
  names:
    kind: ControlPlaneInfo
    listKind: ControlPlaneInfoList
    plural: controlplaneinfos
    singular: controlplaneinfo
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Node
      type: string
      jsonPath: .spec.nodeName
    - name: Last Sensed
      type: string
      jsonPath: .status.lastSensed
{{- end }}
{{- end }}
