kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubescape.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubescape.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubescape.name }}
  namespace: {{ .Values.ksNamespace }}
