{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubescape.name }}
  labels:
    kubescape.io/ignore: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubescape.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubescape.name }}
  namespace: {{ .Values.ksNamespace }}
{{ end }}
