{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescape.name "tier" .Values.global.namespaceTier) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kubescape.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubescape.name }}
  namespace: {{ .Values.ksNamespace }}
{{ end }}
