{{- $cloud_provider := (include "cloud_provider" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.armoKubescape.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.armoKubescape.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.armoKubescape.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.armoKubescape.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        tier: {{ .Values.global.namespaceTier}}
        app: {{ .Values.armoKubescape.name }}
    spec:
      containers:
      - name: kubescape
        image: "{{ .Values.armoKubescape.image.repository }}:{{ .Values.armoKubescape.image.tag }}"
        imagePullPolicy: "{{ .Values.armoKubescape.image.pullPolicy }}"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: KS_DOWNLOAD_ARTIFACTS  # When set to true the artifacts will be downloaded every scan execution
          value: "{{ .Values.armoKubescape.downloadArtifacts }}" 
        - name: KS_DEFAULT_CONFIGMAP_NAME
          value: "{{ .Values.armoKubescape.name }}-config"
        - name: KS_DEFAULT_CONFIGMAP_NAMESPACE
          value: "{{ .Values.armoNameSpace }}"
        - name: KS_ENABLE_HOST_SCANNER
          value: "{{ .Values.armoKubescape.enableHostScan }}"
        - name: KS_SUBMIT
          value: "{{ .Values.armoKubescape.submit }}"
        - name: KS_SKIP_UPDATE_CHECK
          value: "{{ .Values.armoKubescape.skipUpdateCheck }}"
        - name: KS_SAAS_ENV
        {{ if eq .Values.environment "dev" }}
          value: "dev"
        {{- else if eq .Values.environment "staging" }}
          value: "staging"
        {{- else }}
          value: ""
        {{- end }}
        {{- if $cloud_provider }}
        - name: KS_CLOUD_PROVIDER
          value: "{{ $cloud_provider }}"
        - name: KS_CLOUD_REGION
          value: "{{ .Values.cloudRegion }}"
        - name: KS_KUBE_CLUSTER
          value: "{{ .Values.clusterName }}"
        {{- if eq "gke" $cloud_provider }}
        - name: KS_GKE_PROJECT
          value: "{{ .Values.gkeProject }}"
        {{- end -}}
        {{- end }}
        command:
        - ksserver
        resources:
{{ toYaml .Values.armoKubescape.resources | indent 14 }}            
        volumeMounts:
        - name: kubescape-config-volume
          mountPath: /home/armo/.kubescape/config.json
          subPath: config.json
        - name: host-scanner-definition
          mountPath: /home/armo/.kubescape/host-scanner.yaml
          subPath: host-scanner-yaml
      serviceAccountName: {{ .Values.global.armoKubescapeServiceAccountName }}
      automountServiceAccountToken: true
      volumes:
      - name: kubescape-config-volume
        configMap:
          name: {{ .Values.armoKubescape.name }}-config
      - name: host-scanner-definition
        configMap:
          name: host-scanner-definition
