{{- if and .Values.armoVulnScanScheduler.enabled .Values.armoKubescape.submit }}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ .Values.armoVulnScanScheduler.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoVulnScanScheduler.name }}
    tier: {{ .Values.global.namespaceTier}}
    armo.tier: "kubescape-scan"
spec:
  schedule: "{{ .Values.armoVulnScanScheduler.scanSchedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            armo.tier: "kubescape-scan"
        spec:
          containers:
          - name: {{ .Values.armoVulnScanScheduler.name }}
            image: "{{ .Values.armoVulnScanScheduler.image.repository }}:{{ .Values.armoVulnScanScheduler.image.tag }}"
            imagePullPolicy: {{ .Values.armoVulnScanScheduler.image.pullPolicy }}
            args: 
              - -method=post
              - -scheme=http
              - -host={{ .Values.armoWebsocket.name }}:{{ .Values.armoWebsocket.service.port }}
              - -path=v1/triggerAction
              - -headers="Content-Type:application/json"
              - -path-body=/home/ks/request-body.json
            volumeMounts:
              - name: {{ .Values.armoVulnScanScheduler.name }}
                mountPath: /home/ks/request-body.json
                subPath: request-body.json
                readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 14 }}
{{- end }}
{{- if .Values.armoVulnScanScheduler.volumeMounts }}
{{ toYaml .Values.armoVulnScanScheduler.volumeMounts | indent 14 }}
{{- end }}
          restartPolicy: Never
          automountServiceAccountToken: false
          volumes:
          - name: {{ .Values.armoVulnScanScheduler.name }}
            configMap:
              name: {{ .Values.armoVulnScanScheduler.name }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 10 }}
{{- end }}
{{- if .Values.armoVulnScanScheduler.volumes }}
{{ toYaml .Values.armoVulnScanScheduler.volumes | indent 10 }}
{{- end }}
{{- end }}
