apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.armoKubescape.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}
spec:
  type: {{ .Values.armoKubescape.service.type }}
  ports:
    - name: http
      port: {{ .Values.armoKubescape.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.armoKubescape.name }}