{{- if .Values.armoCollector.enabled  }}
{{ template "account_guid" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.armoCollector.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoCollector.name }}
    tier: {{ .Values.global.namespaceTier}}
spec:
  replicas: {{ .Values.armoCollector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.armoCollector.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.armoCollector.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.global.namespaceTier}}
        app: {{ .Values.armoCollector.name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.armoCollector.name }}
          image: "{{ .Values.armoCollector.image.repository }}:{{ .Values.armoCollector.image.tag }}"
          imagePullPolicy: {{ .Values.armoCollector.image.pullPolicy }}
          ports:
            - name: "readiness-port"
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: readiness-port
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
{{ toYaml .Values.armoCollector.resources | indent 12 }}
          env:
            - name: CA_K8S_REPORT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.beConfig }}
                  key: eventReceiverWS
            - name: CA_CUSTOMER_GUID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.beConfig }}
                  key: accountGuid
            - name: CA_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.beConfig }}
                  key: clusterName
            {{- range .Values.armoCollector.env }}
            - name: {{ .name  }}
              value: "{{ .value }}"
            {{- end }}
          args:
            - -include-namespaces={{ .Values.armoNameSpace }}
            - 2>&1
      volumes:
        - name: {{ .Values.global.beConfig }}
          configMap:
            name: {{ .Values.global.beConfig }}
            items:
            - key: "clusterData"
              path: "clusterData.json"
      serviceAccountName: {{ .Values.global.armoServiceAccountName }}
      automountServiceAccountToken: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}