{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.name }}
  labels:
    kubescape.io/ignore: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["sbomsyfts"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["applicationactivities", "applicationprofiles", "networkneighborses", "sbomsyftfiltereds"]
  verbs: ["create", "get", "update", "watch", "list", "patch"]
{{- end }}
