apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: {{ .Values.kubescapeScheduler.name }}
      namespace: {{ .Values.ksNamespace }}
      labels:
        app: {{ .Values.kubescapeScheduler.name }}
        tier: {{ .Values.global.namespaceTier}}
        armo.tier: "kubescape-scan"
    spec:
      schedule: "{{ .Values.kubescapeScheduler.scanSchedule }}"
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                armo.tier: "kubescape-scan"
            spec:
              {{- if .Values.imagePullSecrets }}
              imagePullSecrets:
              - name: {{ toYaml .Values.imagePullSecrets }}
              {{- end }}
              containers:
              - name: {{ .Values.kubescapeScheduler.name }}
                image: "{{ .Values.kubescapeScheduler.image.repository }}:{{ .Values.kubescapeScheduler.image.tag }}"
                imagePullPolicy: {{ .Values.kubescapeScheduler.image.pullPolicy }}
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 100
                args: 
                  - -method=post
                  - -scheme=http
                  - -host={{ .Values.operator.name }}:{{ .Values.operator.service.port }}
                  - -path=v1/triggerAction
                  - -headers="Content-Type:application/json"
                  - -path-body=/home/ks/request-body.json
                volumeMounts:
                  - name: "request-body-volume"
                    mountPath: /home/ks/request-body.json
                    subPath: request-body.json
                    readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 18 }}
{{- end }}
{{- if .Values.kubescapeScheduler.volumeMounts }}
{{ toYaml .Values.kubescapeScheduler.volumeMounts | indent 18 }}
{{- end }}
              restartPolicy: Never
              automountServiceAccountToken: false
              volumes:
                - name: "request-body-volume" # placeholder
                  configMap:
                    name: {{ .Values.kubescapeScheduler.name }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 16 }}
{{- end }}
{{- if .Values.kubescapeScheduler.volumes }}
{{ toYaml .Values.kubescapeScheduler.volumes | indent 16 }}
{{- end }}
          