{{- $components := fromYaml (include "components" .) }}
{{- if and .Values.global.networkPolicy.enabled .Values.global.networkPolicy.createEgressRules $components.autoUpdater.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.helmReleaseUpgrader.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    app: {{ .Values.helmReleaseUpgrader.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.helmReleaseUpgrader.name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Egress
  egress:
{{ tpl (.Files.Get "assets/common-egress-rules.yaml") . | indent 4 }}
{{- end }}
