{{- if eq .Values.capabilities.autoUpgrading "enable" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    kubescape.io/ignore: "true"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    kubescape.io/ignore: "true"
subjects:
- kind: ServiceAccount
  name: {{ .Values.helmReleaseUpgrader.name }}
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: {{ .Values.helmReleaseUpgrader.name }}
{{ end }}
