{{- if and .Values.gateway.enabled .Values.kubescape.submit }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  type: {{ .Values.gateway.httpService.type }}
  ports:
    - port: {{ .Values.gateway.websocketService.port }}
      targetPort: {{ .Values.gateway.websocketService.targetPort }}
      protocol: {{ .Values.gateway.websocketService.protocol }}
      name: "websocket"
    - port: {{ .Values.gateway.httpService.port }}
      targetPort: {{ .Values.gateway.httpService.targetPort }}
      protocol: {{ .Values.gateway.httpService.protocol }}
      name: "http"
  selector:
    app: {{ .Values.gateway.name }}
{{- end }}
