kind: ConfigMap 
apiVersion: v1 
metadata:
  name: host-scanner-definition
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.global.cloudConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  host-scanner-yaml: |-
{{ tpl (.Files.Get "assets/host-scanner-definition.yaml") . | indent 4}}