kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.operatorServiceAccountName }}-roles
  namespace: {{ .Values.ksNamespace }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]