kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.cloudSecret }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.global.cloudSecret }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/infra: credentials
type: Opaque
data:
  account: {{ .Values.account | default "" | b64enc }}
  accessKey: {{ .Values.accessKey | default "" | b64enc }}
