{{- $components := fromYaml (include "components" .) }}
{{- if $components.cloudSecret.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $components.cloudSecret.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    app: {{ $components.cloudSecret.name }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/infra: credentials
    kubescape.io/ignore: "true"
type: Opaque
data:
  account: "{{ .Values.account | default "" | b64enc }}"
  accessKey: "{{ .Values.accessKey | default "" | b64enc }}"
{{- end }}
