kind: ConfigMap
apiVersion: v1
metadata:
  name: ks-capabilities
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: ks-capabilities
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
data:
  capabilities: |
    {
      "capabilities": {{- .Values.capabilities | toJson }},
      "components": {{- include "components" . | fromYaml | toJson }},
      "configurations": {{- .Values.configurations | toJson }}
    }
