{{- if not (.Capabilities.APIVersions.Has "batch/v1/CronJob") }}
  {{- fail "`batch/v1/CronJob not supported`" }}
{{- end }}
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: kubevuln-cronjob-template # TODO: update template name
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.global.cloudConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/kubevuln-cronjob-full.yaml") . }}
