apiVersion: v2
name: kubescape-service-discovery-result-crd
description: A Helm chart CRDs for Kubescape Operator for service authentication discovery

type: application

version: 0.0.1

appVersion: "0.0.1"
