{{- if and (eq (include "relevancy.Enabled" .) "true") .Values.storage.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.ClusterRole }}
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "nodes", "deployments", "daemonsets", "statefulsets", "jobs", "cronjobs", "replicasets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch"]
{{- end}}