{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
{{- $no_proxy_envar_list := (include "no_proxy_envar_list" .) -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.nodeAgent.daemonset.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
      app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.nodeAgent.daemonset.name }}
      tier: {{ .Values.global.namespaceTier}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.global.namespaceTier}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app: {{ .Values.nodeAgent.daemonset.name }}
        alt-name: {{ .Values.nodeAgent.daemonset.name }} # Why?
      {{- if .Values.otelCollector.enabled }}
        otel: enabled
      {{- end }}
      {{- if .Values.global.addRevisionLabel }}
        helm.sh/revision: "{{ .Release.Revision }}"
      {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                # - ppc64le
                # - s390x
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      serviceAccountName: {{ .Values.nodeAgent.ServiceAccount }}
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      volumes:
        {{- range .Values.nodeAgent.volumes }}
        - name: {{ .name }}
        {{- if .configMap}}
          configMap: 
            name: {{ .configMap.name }}
        {{ else if .emptyDir }}
          emptyDir: {}
        {{ else if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
        {{- end }}
        {{- end }}       
        {{- if ne .Values.global.proxySecretFile ""}}
        - name: proxy-secret
          secret:
            secretName: {{ .Values.global.proxySecretName }}
        {{- end }}    
      initContainers:
      - env:
        {{- range .Values.nodeAgent.initContainer.env }}
        - name: {{ .name  }}
        {{- if .value }}
          value: "{{ .value }}"
        {{- end }}
        {{- end }}
        image: "{{ .Values.nodeAgent.initContainer.image.repository }}:{{ .Values.nodeAgent.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.nodeAgent.initContainer.image.pullPolicy }}
        name: {{ .Values.nodeAgent.initContainer.name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        {{- range .Values.nodeAgent.initContainer.volumeMounts }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
          readOnly: {{ .readOnly }}
        {{- end }}
      containers:
        - name: {{ .Values.nodeAgent.containers.nodeAgent.name }}
          image: "{{ .Values.nodeAgent.containers.nodeAgent.image.repository }}:{{ .Values.nodeAgent.containers.nodeAgent.image.tag }}"
          imagePullPolicy: {{ .Values.nodeAgent.containers.nodeAgent.image.pullPolicy }}
          resources:
{{ toYaml .Values.nodeAgent.resources | indent 12 }}
          env:
            - name: KS_LOGGER_LEVEL
              value: "{{ .Values.logger.level }}"
            - name: KS_LOGGER_NAME
              value: "{{ .Values.logger.name }}"
            {{- if .Values.otelCollector.enabled }}
            - name: OTEL_COLLECTOR_SVC
              value: "otel-collector:4317"
            {{- end }}
            {{- if ne .Values.global.httpsProxy ""}}
            - name: HTTPS_PROXY
              value: "{{ .Values.global.httpsProxy }}"
            - name : no_proxy
              value: "{{ $no_proxy_envar_list }}"
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range .Values.nodeAgent.containers.nodeAgent.env }}
            - name: {{ .name  }}
            {{- if .value }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_RESOURCE
                - SYS_ADMIN
          volumeMounts:
          {{- range .Values.nodeAgent.containers.nodeAgent.volumeMounts }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
          {{- if ne .Values.global.proxySecretFile ""}}
          - name: proxy-secret
            mountPath: /etc/ssl/certs/proxy.crt
            subPath: proxy.crt
          {{- end }}
          
          
{{- end}}