{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.nodeAgent.daemonset.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
      app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.nodeAgent.daemonset.name }}
      tier: {{ .Values.global.namespaceTier}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.nodeAgent.daemonset.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.global.namespaceTier}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app: {{ .Values.nodeAgent.daemonset.name }}
        alt-name: {{ .Values.nodeAgent.daemonset.name }} # Why?
      {{- if .Values.otelCollector.enabled }}
        otel: enabled
      {{- end }}
      {{- if .Values.addRevisionLabel }}
        helm.sh/revision: "{{ .Release.Revision }}"
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.nodeAgent.ServiceAccount }}
      automountServiceAccountToken: {{ .Values.nodeAgent.daemonset.automountServiceAccountToken }}
      volumes:
        {{- range .Values.nodeAgent.volumes }}
        - name: {{ .name }}
        {{- if .configMap}}
          configMap: 
            name: {{ .configMap.name }}
        {{ else if .emptyDir }}
          emptyDir: {}
        {{ else if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
        {{- end }}      
        {{- end }}      
      initContainers:
      - env:
        {{- range .Values.nodeAgent.initContainer.env }}
        - name: {{ .name  }}
        {{- if .value }}
          value: "{{ .value }}"
        {{- end }}
        {{- end }}
        image: "{{ .Values.nodeAgent.initContainer.image.repository }}:{{ .Values.nodeAgent.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.nodeAgent.initContainer.image.pullPolicy }}
        name: {{ .Values.nodeAgent.initContainer.name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        {{- range .Values.nodeAgent.initContainer.volumeMounts }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
          readOnly: {{ .readOnly }}
        {{- end }}
      containers:
        - name: {{ .Values.nodeAgent.containers.nodeAgent.name }}
          image: "{{ .Values.nodeAgent.containers.nodeAgent.image.repository }}:{{ .Values.nodeAgent.containers.nodeAgent.image.tag }}"
          imagePullPolicy: {{ .Values.nodeAgent.containers.nodeAgent.image.pullPolicy }}
          env:
            - name: KS_LOGGER_LEVEL
              value: "{{ .Values.logger.level }}"
            - name: KS_LOGGER_NAME
              value: "{{ .Values.logger.name }}"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range .Values.nodeAgent.containers.nodeAgent.env }}
            - name: {{ .name  }}
            {{- if .value }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          securityContext:
            runAsUser: {{ .Values.nodeAgent.containers.nodeAgent.securityContext.user }}
            capabilities:
              add: 
                {{- range .Values.nodeAgent.containers.nodeAgent.securityContext.capabilities.add }}
                - {{ .name }}
                {{- end }}
          volumeMounts:
          {{- range .Values.nodeAgent.containers.nodeAgent.volumeMounts }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
{{- end}}